[package]
name = "rastro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slog = "2.7.0"
slog-scope = "4.4.0"
slog-envlogger = "2.2.0"

